- .pre-commit-config.yaml
- app/constants.py
- app/create_mysql_db.py
- app/main.py
- app/model_base.py
- app/player/view.py
este metodo se encarga de tomar un nombre y crear una nuevo jugador.
Devuelve la informacion pertinente
> Lcvw 49 add register login

- app/card/view.py
- app/constants.py
- app/model_base.py
- app/player/models.py
- app/tests/test_card.py
- package.json
Reverts LCVW-Las-Chicas-Superpoderosas/Ing_Soft2023_La_Cosa#9
> Revert "Lcvw 41 create effect module (FIX TESTS)"

- app/card/effects_mapping.py
- app/card/view.py
- app/constants.py
- app/create_mysql_db.py
- app/game/view.py
- app/model_base.py
- app/tests/test_card.py
- app/tests/test_create_game.py
- app/tests/test_model_base.py
- app/tests/test_utils.py
- package.json
Fixed the tests files that where broken
Add some hardinnes to the code, improving edge cases.
Modify model_base so is more versatile now
> Lcvw 41 fix tests and some bugs

- app/game/view.py
> fix validation

- app/game/models.py
- app/game/view.py
- app/main.py
not adding test files for now, test locally
> Lcvw 27 join game

- app/card/view.py
The frontend asked us to change this response
> LCVW-41-Fix_Respose_From_play_targeted_card

- app/game/view.py
- app/tests/test_create_game.py
npm run test now passes all tests right after cloning the repo
> fix(_player_exists): update function call

- app/constants.py
- app/game/models.py
- app/game/view.py
- app/player/models.py
- app/tests/test_game.py
- app/tests/test_utils.py
Aded next Turn endpoint
Problems: Mysql cant store list neither arrays. we solved this using json arrays
Maybe not the best solution but it works pretty solid.
Also added tests
> Lcvw 14 Add next turn

- app/card/models.py
- app/main.py
- app/statics/cards.txt
script to automatically upload images to the database respecting the schema of the iamges in the front
> added script to automatically upload the images

- app/game/models.py
- app/game/view.py
- app/main.py
- app/player/models.py
- app/tests/test_utils.py
> add repartit cartas

- app/card/view.py
- app/game/models.py
- app/tests/test_card.py
add game over validation after we play a card
> add game over

- app/game/models.py
- app/game/view.py
- app/tests/test_game.py
- app/tests/test_utils.py
> fix tests, necesita arreglar el pre-commit

- app/tests/test_card.py
- app/tests/test_game.py
- app/tests/test_utils.py
Adding atomicity to the tests.
Now it wont fail all test if one failed
> fix tests: adding atomicity

- app/card/view.py
- app/game/models.py
- app/game/view.py
- app/player/models.py
- app/tests/test_card.py
- app/tests/test_game.py
- app/tests/test_utils.py
Added the game over validations required to over the game...
so yep thats it, if the thing dies game over  humans winif all humans are infected or all humans are  game over the thing win
I must add a infected value
Also fix the tests pls add the another pr first to avoid merge problems
Fixed the requests parameters when playing a card (change id_usuario to id_player)
DONT PUSH THIS UNLESS YOU ALREADY PUSHED THE TESTS PR
I'M WATCHING U ...
> Lcvw 67 add game over validations

- app/card/view.py
- app/game/models.py
- app/tests/test_card.py
- app/tests/test_game.py
- app/tests/test_utils.py
Fixed the requests parameters.
Also fix the tests pls add the another pr first to avoid merge problems
Fixed the requests parameters when playing a card (change id_usuario to id_player)
**DONT PUSH THIS UNLESS YOU ALREADY PUSHED THE TESTS PR**
_I'M WATCHING U_ ...
> add: turn validations, tests, fix requests parameters

- app/game/view.py
quick fix (fix identation /game endpoint in view.py)
> Lcvw 83 fix bug endpoint /game

- app/game/models.py
- app/game/view.py
- app/main.py
- app/tests/test_game.py
- app/tests/test_utils.py
[tickets1.txt](https://github.com/LCVW-Las-Chicas-Superpoderosas/Ing_Soft2023_La_Cosa/files/12851986/tickets1.txt)
Leer txt
> Lcvw 16/lcvvw 32/lcvw 35 1er sprint

- app/card/view.py
- app/game/models.py
- app/game/view.py
- app/player/models.py
- app/tests/test_utils.py
Fix the turns logic so the front can handle the positions of the players too
> LCVW-68-Change-turns-logic

- app/game/view.py
- app/tests/test_game.py
- app/tests/test_utils.py
deal cards functionality in start game commented until a proper fix is proposed and reviewed. Deal cards test suite  broken as well
> Lcvw 82 get game status

- app/game/models.py
- app/main.py
- app/tests/test_game.py
> Lcvw 87 bug fix endpoint put/hand/y  test

- app/game/models.py
- app/game/view.py
- app/player/models.py
- app/tests/test_game.py
Added the leave game endponit
added leave game test
fix some stylng in code
> LCVW-70-Leave-Game

- app/card/effects_mapping.py
>  Efecto Cambio de LugaR!

- app/tests/test_game.py
add test case of player is host
> LCVW-112-leave-game-test

- app/game/models.py
- app/game/view.py
- app/tests/test_game.py
- app/tests/test_utils.py
Para testear, se puede hacer
npm run start-server -- --test=true
en un browser
localhost:8000/docs
execute start/game
execute put/hand hasta que quede 1 carta
fijarse en mysql los valores con 
select * from game;   (Se puede observar que ya no hay duplicados)
Anadir algunas cartas a discard_pile, asi cuando se queda el deck sin cartas, que se reponga (En un juego real, discard_pile no seria null, pero en esta simulacionm envez de hacer calls a play_card, podes hacer lo siguiente:)
UPDATE game SET discard_pile = '[2, 43, 3]' WHERE id=1;
luego el ultimo execute put hand y se vuelve a reponer el deck sin INTERNAL SERVER ERROR
> LCVW 144 Fix 2 Deck Bugs

- app/card/view.py
- app/game/models.py
- app/main.py
- app/model_base.py
- app/player/models.py
- app/tests/test_card.py
- app/tests/test_game.py
- app/tests/test_ws.py
- app/ws/view.py
'add ws and testing. i remove some values from odels bcs they are not in use and make the request fail while trying to json serialized it' 
Tested 
pls read this pr carefully, its a new implementation (aint that hard lmao) but pay attention fr
> Lcvw 146 add ws

- app/game/models.py
- app/model_base.py
- app/player/models.py
- app/tests/test_ws.py
- app/ws/view.py
Added new implementation for exchange cards in ws
added next player to status in game status
added tests
> Lcvw 151 add exchenge

- app/model_base.py
- app/ws/view.py
* Correccion al cierre de la conexion ws
* checkeo si existe content para luego checkear si esta el type
> Small fixes exchange

- app/ws/view.py
(probably will need to) FIX THE SAME THING IN DIFFERENT BRANCHES FOR THE OTHER DIFFERENT ENDPOINTS
> fix: using await in disconnect calls. 

- app/game/models.py
- app/game/view.py
- app/tests/test_game.py
- app/tests/test_utils.py
endpoint top card, para que el front pueda renderear la carta del mazo al principio de la partida a todos los jugadores y no solo a el host.
se necesita mergear lcvw 161 primero
> Lcvw 162 endpoint top card

- app/card/effects_mapping.py
- app/card/models.py
- app/card/view.py
- app/constants.py
- app/game/models.py
- app/game/view.py
- app/model_base.py
- app/player/models.py
- app/tests/test_ws.py
- app/ws/view.py
add play hand and defense for cards
add method to get the defense cards for atack cards
fix some bugs of ws
> Lcvw 146 add ws to effects

- app/tests/test_ws.py
> add test fix to ws tests

- app/tests/test_ws.py
- app/ws/view.py
added do_defense to handle when target dont want to defense
add the thing exchange with player to infec
> add do defense and card exchange of infection with the thing
